const express = require('express');
const bodyParser = require('body-parser'); // gives ready-to-use middlewares for parsing request bodies

const app = express();

// <--all this is unnecessary with body-parser, woo!
// app.use((req, res, next) => {
//     let body = ''; // empty string for response body
//     req.on('end', () => {
//         const userName = body.split('=')[1]  //takes response of username=suchNsuch and returns just suchNsuch
//         if (userName){ // make it conditional to prevent below from firing w/o data and returning undefined
//             req.body = { name: userName };
//         }
//         next(); //called next within end handler so that we only proceed to next middleware once data is parsed
//     });
//     req.on('data', chunk => {
//         body += chunk;
//     });
// })

app.use(bodyParser.urlencoded({ extended: false }));

app.post('/user', (req, res, next) => {  
    res.send('<h1>User: ' + req.body.userName + '</h1>'); 
}) 
// applies middleware only to the http verb POST
// body auto-generated by bodyParser above. userName comes from res below

app.get('/', (req, res, next) => { 
    res.send('<form action="/user" method="POST"><input type="text" name="userName"><button type="submit">Create User</button></form>')
})
// get needs two args: path, and http method
app.listen(5000);

// npm install nodemon --save-dev   <--auto restart server
// add--> "start": "nodemon fileName.js" to package.json 
// then in terminal >> npm start << and yer golden

// also>> npm install body-parser --save
